const contractAddress = "0x5b4e69F8F96ebcA46c940BDbAd77D03d4E1B0ED9"; // Replace with your own contract address
const chain = 'rinkeby'; // rinkeby, polygon, or ethereum

const welcome_h1 = "Tuning In - Here for the Music!";
const welcome_h2 = "Connect your wallet to join the Club.";
const welcome_p = 'Tuning In NFTs is a tokenized Music Discovery and Distribution Club. A collection of 5500 unique membership tokens is grooving onto the Ethereum blockchain to unite independent artists and passionate listeners around the world. Peace, love, and music NFTs.';
const h1_presale_coming_soon = "Our NFT Drop is Coming Soon!!";
const h1_presale_mint = "Pre-Sale Mint Is Live! Are You Feeling Groovy?";
const h1_public_mint = "Public Mint Is Live! Shake Your Groove thing!!";
const h2_presale_coming_soon = "Pre-Sale Minting Countdown - The Best is Yet to Come!";
const h2_presale_mint = "Public Minting Countdown - It's Almost Time!";
const p_presale_coming_soon = "We are working hard to launch our Groovy Collection. Stay Tuned for Updates!";
const p_presale_mint_not_whitelisted = "You are not GrooveListed for the pre-sale.. 😢";
const p_presale_mint_whitelisted = "You're on the GrooveList! Right On! 🤘🏽";
const p_presale_mint_already_minted = "You've already claimed your GrooveList mint! 🎶 ";
const p_public_mint = "Public Mint is Now Open! 🎉";
const button_presale_coming_soon = "Get on the GrooveList";
const button_presale_mint_whitelisted = "Mint Your Groovy NFT";
const button_presale_mint_not_whitelisted = "Get on the GrooveList";
const button_presale_already_minted = "You're Tuned In! Join the Club!";
const button_public_mint = "Mint Your NFT";
const mint_failed = "Oh no! Minting failed. 💔  Please try again.";
